---
# - name: Stop and disable Firewall
#   service:
#     name=ufw
#     state=stopped
#     enabled=false
#   when: handle_firewall and disable_firewall

- name: Check current timezone
  command: cat /etc/timezone
  register: current_timezone

- name: Set the timezone config file
  copy:
    content={{ timezone }}
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
  when: current_timezone.stdout != timezone

- name: Enable timezone settings
  command: "dpkg-reconfigure --frontend noninteractive tzdata"
  when: current_timezone.stdout != timezone

- name: Start chrony service
  service:
    name=chrony
    state=started
    enabled=true
