---
- name: Stop and disable Firewall
  service:
    name=firewalld
    state=stopped
    enabled=false
  when: handle_firewall and disable_firewall

- name: Check current timezone
  stat:
    path=/etc/localtime
  register: current_timezone

- name: Change the timezone
  command: timedatectl set-timezone {{ timezone }}
  when: current_timezone.stat.lnk_source is not defined or timezone != current_timezone.stat.lnk_source | regex_replace('/usr/share/zoneinfo/', '')

- name: Start chronyd service
  service:
    name=chronyd
    state=started
    enabled=true

- name: Stop and disable NetworkManager
  service:
    name=NetworkManager
    state=stopped
    enabled=false
  when: disable_networkmanager